version: '2'
services:

  base:
    image: hello-world
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:12201
    volumes:
      - ./monitoring/jolokia-jvm-1.3.5-agent.jar:/jolokia-jvm-1.3.5-agent.jar

  hell0-spring-boot:
    image: test/hell0-spring-boot
    command: -javaagent:/jolokia-jvm-1.3.5-agent.jar=port=7777,host=0.0.0.0,discoveryEnabled=false -Xmx512m -jar /app.jar
    ports:
      - "8081:8080"
    extends:
      service: base
